trigger:
  branches:
    include:
      - main

pool:
   name: SelfHostedPool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Choose a Node.js version compatible with your Angular version
  displayName: 'Install Node.js'

- script: |
   npm install -g @angular/cli
   npm install
   ng build --prod
  displayName: 'Build Angular Application'

- task: CopyFiles@2
  inputs:
    contents: 'dist/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files'
  
- script: |
    echo "Contents of Build Artifact Directory:"
    dir $(Build.ArtifactStagingDirectory)
  displayName: 'Verify Files in Artifact Staging Directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureSubscription'
    appName: 'angularAppTestDemo'
    package: '$(Build.ArtifactStagingDirectory)/drop/**/*'
    appType: 'webApp'
  displayName: 'Deploy to Azure App Service'


variables:
  system.debug: true