trigger:
  branches:
    include:
      - main

pool:
  name: SelfHostedPool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Choose a Node.js version compatible with your Angular version
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
    echo "Build complete. Checking output directory."
    dir dist/singtel-movie-front-end/  
  displayName: 'Clean and Build Angular Application'

- task: CopyFiles@2
  inputs:
    contents: 'dist/singtel-movie-front-end/**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureSubscription'
    appName: 'angularAppTestDemo'
    package: '$(Build.ArtifactStagingDirectory)/dist/singtel-movie-front-end/**/*'
    appType: 'webApp'
  displayName: 'Deploy to Azure App Service'