trigger:
  branches:
    include:
      - main

pool:
  name: SelfHostedPool

variables:
  system.debug: true

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration=production
  displayName: 'Build Angular Application'

- task: CopyFiles@2
  displayName: 'Copy files to Artifact Staging Directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist/singtel-movie-front-end'  # Ensure this matches your angular.json outputPath
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/drop'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureSubscription'
    appName: 'angularAppTestDemo'
    package: '$(Build.ArtifactStagingDirectory)/drop'
    appType: 'webApp'
  displayName: 'Deploy to Azure App Service'
