trigger:
  branches:
    include:
      - main

pool:
   name: SelfHostedPool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Choose a Node.js version compatible with your Angular version
  displayName: 'Install Node.js'

- script: |
   npm install -g @angular/cli
   npm install
   ng build --prod --output-path=dist/singtel-movie-front-end --aot --optimization
  displayName: 'Build Angular Application'

- task: CopyFiles@2
  displayName: 'Copy files to Artifact Staging Directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist/singtel-movie-front-end'  # Correct path to the dist folder
    Contents: '**/*'  # Wildcard to include all files
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Ensure the target folder is inside the artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Path to publish the drop folder
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureSubscription'
    appName: 'angularAppTestDemo'
    package: '$(Build.ArtifactStagingDirectory)'  # Correct path to package
    appType: 'webApp'
  displayName: 'Deploy to Azure App Service'

variables:
  system.debug: true